[package]
name = "snarkos"
version = "2.0.2"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
    "aleo",
    "cryptography",
    "blockchain",
    "decentralized",
    "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.66"

[workspace]
members = [
    "account",
    "cli",
    "display",
    "node",
    "node/cdn",
    "node/consensus",
    "node/env",
    "node/messages",
    "node/metrics",
    "node/rest",
    "node/router",
    "node/tcp",
    ".integration",
]

[[bin]]
name = "snarkos"
path = "snarkos/main.rs"

[features]
default = [ "jemalloc" ]
jemalloc = [ "tikv-jemallocator" ]

[workspace.dependencies.snarkvm]
#path = "../snarkVM"
#git = "https://github.com/AleoHQ/snarkVM.git"
#rev = "d916cef"
version = "=0.11.7"
features = ["circuit", "console", "rocks"]

[dependencies.anyhow]
version = "1.0.70"

[dependencies.clap]
version = "4.4"
features = ["derive"]

[dependencies.once_cell]
version = "1"

[dependencies.snarkos-account]
path = "./account"

[dependencies.snarkos-cli]
path = "./cli"

[dependencies.snarkos-display]
path = "./display"

[dependencies.snarkos-node]
path = "./node"

[dependencies.snarkos-node-cdn]
path = "./node/cdn"

[dependencies.snarkos-node-consensus]
path = "./node/consensus"

[dependencies.snarkos-node-env]
path = "./node/env"

[dependencies.snarkos-node-messages]
path = "./node/messages"

[dependencies.snarkos-node-rest]
path = "./node/rest"

[dependencies.snarkos-node-router]
path = "./node/router"

[dependencies.snarkos-node-tcp]
path = "./node/tcp"

[dependencies.tikv-jemallocator]
version = "0.5"
optional = true

[dev-dependencies.rusty-hook]
version = "0.11.2"

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 2
lto = "thin"
incremental = true

[profile.test]
opt-level = 2
lto = "thin"
incremental = true
debug = true
debug-assertions = true
