[package]
name = "snarkos-node-rest"
version = "0.9.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A REST API server for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[features]
default = [ "parallel" ]
parallel = [ "rayon" ]

[dependencies.anyhow]
version = "1.0.70"

[dependencies.axum]
version = "0.6"
features = ["headers"]

[dependencies.axum-extra]
version = "0.7.4"
features = ["erased-json"]

[dependencies.http]
version = "0.2"

[dependencies.indexmap]
version = "2.0"

[dependencies.jsonwebtoken]
version = "8.3"

[dependencies.once_cell]
version = "1.18"

[dependencies.parking_lot]
version = "0.12"

[dependencies.serde]
version = "1"
default-features = false
features = [ "derive" ]

[dependencies.snarkos-node-consensus]
path = "../consensus"

[dependencies.snarkos-node-env]
path = "../env"

[dependencies.snarkos-node-messages]
path = "../messages"

[dependencies.snarkos-node-router]
path = "../router"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"
optional = true

[dependencies.snarkvm]
workspace = true

[dependencies.time]
version = "0.3"

[dependencies.tokio]
version = "1"

[dependencies.tower-http]
version = "0.4"
features = ["cors", "trace"]

[dependencies.tracing]
version = "0.1"
